# Generated by Django 4.2 on 2023-04-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=500)),
                ('customer_last_name', models.CharField(max_length=500)),
                ('customer_address', models.CharField(max_length=500)),
                ('customer_post_code', models.IntegerField()),
                ('customer_phone', models.IntegerField()),
            ],
        ),
    ]
